services:
  auth:
    container_name: dev-auth
    image: auth-service
    build:
      context: .
      dockerfile: ./auth-service/Dockerfile

    ports:
      - 5000:5000
      - 27017:27017
    volumes:
      - ./auth-service:/app

  front:
    container_name: dev-front
    image: dev-front
    build:
        context: .
        dockerfile: ./front/Dockerfile
    ports:
      - 5001:5000
    volumes:
      - ./front:/app
