services:
  auth:
    container_name: dev-auth
    image: auth-service
    build:
      context: .
      dockerfile: ./auth-service/Dockerfile

    ports:
      - 5000:5000
    volumes:
      - ./auth-service:/app

  # front:
  #   container_name: dev-front
  #   image: python:3.10.7-bullseye
  #   ports:
  #     - 3001:3000
  #   volumes:
  #     - ./front:/app
